# Generated by Django 3.1.5 on 2021-03-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('sumn', models.CharField(max_length=100)),
            ],
        ),
    ]
